# Generated by Django 5.2.6 on 2025-10-01 16:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quadro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.PositiveSmallIntegerField(choices=[(1, 'Quadro 1 (Grande à esquerda)'), (2, 'Quadro 2 (Retangular em cima à direita)'), (3, 'Quadro 3 (Quadrado pequeno à direita - esquerda)'), (4, 'Quadro 4 (Quadrado pequeno à direita - direita)')], unique=True, verbose_name='Posição do Quadro')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('imagem', models.ImageField(upload_to='quadros/', verbose_name='Imagem')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link (opcional)')),
            ],
        ),
        migrations.AlterField(
            model_name='tiinforma',
            name='descricao',
            field=ckeditor.fields.RichTextField(verbose_name='Descrição'),
        ),
    ]
