# Generated by Django 5.2.6 on 2025-10-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0002_quadro_alter_tiinforma_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cargo', models.CharField(max_length=255, verbose_name='Cargo')),
                ('data_admissao', models.DateField(verbose_name='Data de Admissão')),
            ],
            options={
                'ordering': ['data_admissao'],
            },
        ),
    ]
