# Generated by Django 5.2.6 on 2025-10-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0003_admitido'),
    ]

    operations = [
        migrations.AddField(
            model_name='quadro',
            name='imagem_overlay',
            field=models.ImageField(blank=True, null=True, upload_to='quadros/overlays/', verbose_name='Imagem para Overlay'),
        ),
        migrations.AlterField(
            model_name='quadro',
            name='imagem',
            field=models.ImageField(upload_to='quadros/', verbose_name='Imagem Normal'),
        ),
    ]
