# Generated by Django 5.2.6 on 2025-10-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0004_quadro_imagem_overlay_alter_quadro_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cargo_anterior', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cargo Anterior')),
                ('novo_cargo', models.CharField(max_length=255, verbose_name='Novo Cargo')),
                ('data_promocao', models.DateField(verbose_name='Data da Promoção')),
            ],
            options={
                'ordering': ['data_promocao'],
            },
        ),
    ]
