# Generated by Django 5.2.6 on 2025-10-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0005_promocao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quadro',
            name='posicao',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Quadro 1 (Grande à esquerda)'), (2, 'Quadro 2 (Retangular em cima à direita)'), (3, 'Quadro 3 (Quadrado pequeno à direita - esquerda)'), (4, 'Quadro 4 (Quadrado pequeno à direita - direita)')], null=True, unique=True, verbose_name='Posição do Quadro'),
        ),
    ]
