# Generated by Django 5.2.6 on 2025-11-17 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0006_alter_quadro_posicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quadro',
            name='imagem_overlay',
        ),
    ]
