# Generated by Django 5.2.6 on 2025-11-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0007_remove_quadro_imagem_overlay'),
    ]

    operations = [
        migrations.AddField(
            model_name='quadro',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='quadros/arquivos/', verbose_name='Arquivo (PDF opcional)'),
        ),
        migrations.AddField(
            model_name='quadro',
            name='imagem_overlay',
            field=models.ImageField(blank=True, null=True, upload_to='quadros/overlays/', verbose_name='Imagem para Overlay'),
        ),
    ]
